// LOCALHOST STUDENTS----------------------------------------------
### Get all students
GET http://localhost:8080/students

### Get student by id
GET http://localhost:8080/students/6531f49dd6489985b38789f8

### Create student
POST http://localhost:8080/students HTTP/1.1
content-type: application/json

{
    "firstName": "Meredith",
    "lastName": "Elliott",
    "parentName": "Julie",
    "email": "spackMom@email.com",
    "phone": "(403)123-4567",
    "favoriteSong": "Something Elevator",
    "birthday": "January 1",
    "birthYear": "2018"
}

### PUT student
PUT http://localhost:8080/students/6531f49dd6489985b38789f8 HTTP/1.1
content-type: application/json

{
    "firstName": "Meredith",
    "lastName": "Samsonite",
    "parentName": "Julie",
    "email": "spackMom@email.com",
    "phone": "(403)123-4567",
    "favoriteSong": "Something Elevator",
    "birthday": "January 1",
    "birthYear": "2018"
}
### DELETE student
DELETE http://localhost:8080/students/6531f49dd6489985b38789f8 HTTP/1.1


//------------------------------------------------------------------------------------
// LOCALHOST MUSIC BOOKS------------------------------------------
### Get all music books
GET http://localhost:8080/musicBooks

### Get music book by id
GET http://localhost:8080/musicBooks/6531f64ad6489985b38789f9

### Create music book
POST http://localhost:8080/musicBooks HTTP/1.1
content-type: application/json

{
    "title": "Best Book Ever",
    "series": "Popular Series",
    "level": "1000",
    "publisher": "Fisher Price"
}

### PUT music book
PUT http://localhost:8080/musicBooks/6531f64ad6489985b38789f9 HTTP/1.1
content-type: application/json

{
    "title": "Best Book Ever x2",
    "series": "Popular Series",
    "level": "10002",
    "publisher": "Golden Books"
}
### DELETE music book
DELETE http://localhost:8080/musicBooks/6531f64ad6489985b38789f9 HTTP/1.1



//----------------------------------------------------------------------------
//---------------PRODUCTION---------------------------------------------------
//----------------------------------------------------------------------------

// PRODUCTION STUDENTS----------------------------------------------
### Get all students
GET https://js-musicstudents-cse341.onrender.com/students

### Get student by id
GET https://js-musicstudents-cse341.onrender.com/students/6531f49dd6489985b38789f8

### Create student
POST https://js-musicstudents-cse341.onrender.com/students HTTP/1.1
content-type: application/json

{
    "firstName": "Meredith",
    "lastName": "Elliott",
    "parentName": "Julie",
    "email": "spackMom@email.com",
    "phone": "(403)123-4567",
    "favoriteSong": "Something Elevator",
    "birthday": "January 1",
    "birthYear": "2018"
}

### PUT student
PUT https://js-musicstudents-cse341.onrender.com/students/6531f49dd6489985b38789f8 HTTP/1.1
content-type: application/json

{
    "firstName": "Meredith",
    "lastName": "Samsonite",
    "parentName": "Julie",
    "email": "spackMom@email.com",
    "phone": "(403)123-4567",
    "favoriteSong": "Something Elevator",
    "birthday": "January 1",
    "birthYear": "2018"
}
### DELETE student
DELETE https://js-musicstudents-cse341.onrender.com/students/6531f49dd6489985b38789f8 HTTP/1.1


------------------------------------------------------------------------------------
// PRODUCTION MUSIC BOOKS------------------------------------------
### Get all music books
GET https://js-musicstudents-cse341.onrender.com/musicBooks

### Get music book by id
GET https://js-musicstudents-cse341.onrender.com/musicBooks/6531f64ad6489985b38789f9

### Create music book
POST https://js-musicstudents-cse341.onrender.com/musicBooks HTTP/1.1
content-type: application/json

{
    "title": "Best Book Ever",
    "series": "Popular Series",
    "level": "1000",
    "publisher": "Fisher Price"
}

### PUT music book
PUT https://js-musicstudents-cse341.onrender.com/musicBooks/6531f64ad6489985b38789f9 HTTP/1.1
content-type: application/json

{
    "title": "Best Book Ever x2",
    "series": "Popular Series",
    "level": "10002",
    "publisher": "Golden Books"
}
### DELETE music book
DELETE https://js-musicstudents-cse341.onrender.com/musicBooks/6531f64ad6489985b38789f9 HTTP/1.1