# LOCALHOST
### GET
http://localhost:8080

### GET all students
http://localhost:8080/students

### DELETE student (easier up here, out of order; I'm being lazy!)
DELETE http://localhost:8080/students/6528b160f9c2c2f2f99ac46a HTTP/1.1

### GET Gabby (student by id)
http://localhost:8080/students/6528af7374ef262b0d2b1890

### GET Lydia (student by id)
http://localhost:8080/students/6528af7374ef262b0d2b1891

### GET Millie (student by id)
http://localhost:8080/students/6528af7374ef262b0d2b1892

### GET Bryn (student by id)
http://localhost:8080/students/6528af7374ef262b0d2b1894

### GET Henrik (student by id)
http://localhost:8080/students/6528af7374ef262b0d2b1893

### GET newest student by id
http://localhost:8080/students/6528b18af9c2c2f2f99ac46b

### CREATE CONTACT
POST http://localhost:8080/students HTTP/1.1
content-type: application/json

{
    "firstName": "Joshua",
    "lastName": "Bourne",
    "parentName": "Erica",
    "email": "erica@email.com",
    "phone": "(702)123-4567",
    "favoriteSong": "Something Anime",
    "birthday": "January 1",
    "birthYear": "2003"
}

### CREATE CONTACT !!!INCOMPLETE!!!
POST http://localhost:8080/students HTTP/1.1
content-type: application/json

{
    "firstName":"Shirley",
    "email":"shirley@fakeEmail.com",
    "favoriteColor":"pink",
    "birthday":"01/01/1900"
}

### PUT student (edit Henrik by id)
PUT http://localhost:8080/students/6528af7374ef262b0d2b1893 HTTP/1.1
content-type: application/json

{
    "firstName": "Henrik",
    "lastName": "Anvik",
    "parentName": "Jolayne",
    "email": "jolayne@email.com",
    "phone": "(587)123-4567",
    "favoriteSong": "Deep Something",
    "birthday": "January 1",
    "birthYear": "2011"
}

# --------------------------------------------------------------------------
# LOCALHOST BOOKS

### GET all books
http://localhost:8080/musicBooks

### DELETE student (easier up here, out of order; I'm being lazy!)
DELETE http://localhost:8080/musicBooks/6528b160f9c2c2f2f99ac46a HTTP/1.1

### GET Faber & Faber Primer (books by id)
http://localhost:8080/musicBooks/6528b14f74ef262b0d2b18a0

### GET F&F 1 Christmas (books by id)
http://localhost:8080/musicBooks/6528b14f74ef262b0d2b18a5

### GET 2A Piano Adventures (books by id)
http://localhost:8080/musicBooks/6528b14f74ef262b0d2b18a8

### GET F&F 2b Jazz & Blues (books by id)
http://localhost:8080/musicBooks/6528b14f74ef262b0d2b18af

### GET F&F 5 Christmas (books by id)
http://localhost:8080/musicBooks/6528b14f74ef262b0d2b18b9

### CREATE musicBook
POST http://localhost:8080/musicBooks HTTP/1.1
content-type: application/json

{
    "title": "John Thompson 1",
    "series": "John Thompson Lesson Books",
    "level": "1",
    "publisher": "John Thompson"
}

### GET newest books by id
http://localhost:8080/musicBooks/6528b335f9c2c2f2f99ac46c

### CREATE musicBooks !!!INCOMPLETE!!!
POST http://localhost:8080/musicBooks HTTP/1.1
content-type: application/json

{
    "title": "F",
    "series": "",
    "level": "2",
    "publisher": "Hal Leonard"
}

### PUT musicBooks (edit latest by id)
PUT http://localhost:8080/musicBooks/6528b335f9c2c2f2f99ac46c HTTP/1.1
content-type: application/json

{
    "title": "John Thompson 1",
  "series": "John Thompson Lesson Books",
  "level": "1",
  "publisher": "No idea!"
}






# ---------------------------------------------------------------------------
#  PRODUCTION ---------------------------------------------------------------
# ---------------------------------------------------------------------------


### GET all students
https://js-musicstudents-cse341.onrender.com/students

### GET Gabby
https://js-musicstudents-cse341.onrender.com/students/652a1ffabf578bc8b7e04658



### CREATE student
POST https://js-musicstudents-cse341.onrender.com/students HTTP/1.1
content-type: application/json

{
    "firstName": "Samantha",
    "lastName": "Delainey",
    "parentName": "Dawna",
    "email": "dawna@email.com",
    "phone": "(702)123-4567",
    "favoriteSong": "Rudolph",
    "birthday": "January 1",
    "birthYear": "2003"
}

### CREATE student !!!INCOMPLETE!!!
POST https://js-musicstudents-cse341.onrender.com/students HTTP/1.1
content-type: application/json

{
    "firstName": "Samantha",
    "lastName": "d",
    "parentName": "Dawna",
    "email": "dawna@email.com",
    "phone": "(702)123-4567",
    "favoriteSong": "Rudolph",
    "birthday": "January 1",
    "birthYear": "2003"
}

### PUT student (edit Gabby by id)
PUT https://js-musicstudents-cse341.onrender.com/students/6528af7374ef262b0d2b1890 HTTP/1.1
content-type: application/json

{
    "firstName": "Gabby",
    "lastName": "Spackman",
    "parentName": "Julie",
    "email": "spackMom@email.com",
    "phone": "(403)123-4567",
    "favoriteSong": "Something Country",
    "birthday": "January 1",
    "birthYear": "2008"
}


### DELETE contact (delete by id)
DELETE https://js-musicstudents-cse341.onrender.com/students/652a1dd2bf578bc8b7e04656 HTTP/1.1




### GET all books
https://js-musicstudents-cse341.onrender.com/musicBooks

### DELETE book (easier up here, out of order; I'm being lazy!)
DELETE https://js-musicstudents-cse341.onrender.com/musicBooks/652a1e75bf578bc8b7e04657 HTTP/1.1

### GET Faber & Faber Primer (books by id)
https://js-musicstudents-cse341.onrender.com/musicBooks/6528b14f74ef262b0d2b18a0

### GET F&F 1 Christmas (books by id)
https://js-musicstudents-cse341.onrender.com/musicBooks/6528b14f74ef262b0d2b18a5

### GET 2A Piano Adventures (books by id)
https://js-musicstudents-cse341.onrender.com/musicBooks/6528b14f74ef262b0d2b18a8

### GET F&F 2b Jazz & Blues (books by id)
https://js-musicstudents-cse341.onrender.com/musicBooks/6528b14f74ef262b0d2b18af

### GET F&F 5 Christmas (books by id)
https://js-musicstudents-cse341.onrender.com/musicBooks/6528b14f74ef262b0d2b18b9

### CREATE musicBook
POST https://js-musicstudents-cse341.onrender.com/musicBooks HTTP/1.1
content-type: application/json

{
    "title": "John Thompson 1",
    "series": "John Thompson Lesson Books",
    "level": "1",
    "publisher": "John Thompson"
}

### GET newest books by id
https://js-musicstudents-cse341.onrender.com/musicBooks/652a1e75bf578bc8b7e04657

### CREATE musicBooks !!!INCOMPLETE!!!
POST https://js-musicstudents-cse341.onrender.com/musicBooks HTTP/1.1
content-type: application/json

{
    "title": "F",
    "series": "",
    "level": "2",
    "publisher": "Hal Leonard"
}

### PUT musicBooks (edit latest by id)
PUT https://js-musicstudents-cse341.onrender.com/musicBooks/652a1e75bf578bc8b7e04657 HTTP/1.1
content-type: application/json

{
    "title": "John Thompson 1",
  "series": "John Thompson Lesson Books",
  "level": "1",
  "publisher": "No idea!"
}